# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\admin\PycharmProjects\exhibition\vievs\maintesr1.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MonitorManagment(object):
    def setupUi(self, MonitorManagment):
        MonitorManagment.setObjectName("MonitorManagment")
        MonitorManagment.setEnabled(True)
        MonitorManagment.resize(1000, 700)
        MonitorManagment.setMinimumSize(QtCore.QSize(1000, 700))
        MonitorManagment.setMaximumSize(QtCore.QSize(1000, 700))
        self.centralwidget = QtWidgets.QWidget(MonitorManagment)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(441, 81, 500, 400))
        self.graphicsView.setMinimumSize(QtCore.QSize(500, 400))
        self.graphicsView.setMaximumSize(QtCore.QSize(500, 400))
        self.graphicsView.setObjectName("graphicsView")
        self.ProjectorIndicator = QtWidgets.QRadioButton(self.centralwidget)
        self.ProjectorIndicator.setEnabled(False)
        self.ProjectorIndicator.setGeometry(QtCore.QRect(52, 127, 77, 17))
        self.ProjectorIndicator.setObjectName("ProjectorIndicator")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(52, 82, 140, 39))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ScreenIndicator_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.ScreenIndicator_2.setEnabled(False)
        self.ScreenIndicator_2.setGeometry(QtCore.QRect(52, 371, 121, 17))
        self.ScreenIndicator_2.setObjectName("ScreenIndicator_2")
        self.ScreenIndicator_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.ScreenIndicator_1.setEnabled(False)
        self.ScreenIndicator_1.setGeometry(QtCore.QRect(52, 342, 131, 17))
        self.ScreenIndicator_1.setObjectName("ScreenIndicator_1")
        self.ScreenIndicator_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.ScreenIndicator_3.setEnabled(False)
        self.ScreenIndicator_3.setGeometry(QtCore.QRect(52, 400, 121, 17))
        self.ScreenIndicator_3.setObjectName("ScreenIndicator_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(51, 248, 155, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButtonOn = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonOn.setGeometry(QtCore.QRect(50, 150, 75, 23))
        self.pushButtonOn.setObjectName("pushButtonOn")
        self.pushButtonOff = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonOff.setGeometry(QtCore.QRect(140, 150, 75, 23))
        self.pushButtonOff.setObjectName("pushButtonOff")
        self.pushButtonM1Yes = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonM1Yes.setGeometry(QtCore.QRect(240, 340, 75, 23))
        self.pushButtonM1Yes.setObjectName("pushButtonM1Yes")
        self.pushButtonM1No = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonM1No.setGeometry(QtCore.QRect(320, 340, 75, 23))
        self.pushButtonM1No.setObjectName("pushButtonM1No")
        self.pushButtonM3Yes = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonM3Yes.setGeometry(QtCore.QRect(240, 400, 75, 23))
        self.pushButtonM3Yes.setObjectName("pushButtonM3Yes")
        self.pushButtonM3No = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonM3No.setGeometry(QtCore.QRect(320, 400, 75, 23))
        self.pushButtonM3No.setObjectName("pushButtonM3No")
        self.pushButtonM2Yes = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonM2Yes.setGeometry(QtCore.QRect(240, 370, 75, 23))
        self.pushButtonM2Yes.setObjectName("pushButtonM2Yes")
        self.pushButtonM2No = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonM2No.setGeometry(QtCore.QRect(320, 370, 75, 23))
        self.pushButtonM2No.setObjectName("pushButtonM2No")
        self.pushButtonAllMOn = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAllMOn.setGeometry(QtCore.QRect(230, 260, 151, 21))
        self.pushButtonAllMOn.setObjectName("pushButtonAllMOn")
        self.pushButtonAllMOff = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAllMOff.setGeometry(QtCore.QRect(230, 290, 151, 21))
        self.pushButtonAllMOff.setObjectName("pushButtonAllMOff")
        MonitorManagment.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MonitorManagment)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        self.menuRe = QtWidgets.QMenu(self.menubar)
        self.menuRe.setObjectName("menuRe")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menu)
        self.menu_2.setObjectName("menu_2")
        MonitorManagment.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MonitorManagment)
        self.statusbar.setObjectName("statusbar")
        MonitorManagment.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MonitorManagment)
        self.actionClose.setObjectName("actionClose")
        self.actionOpen = QtWidgets.QAction(MonitorManagment)
        self.actionOpen.setObjectName("actionOpen")
        self.action_5 = QtWidgets.QAction(MonitorManagment)
        self.action_5.setObjectName("action_5")
        self.action_7 = QtWidgets.QAction(MonitorManagment)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtWidgets.QAction(MonitorManagment)
        self.action_8.setObjectName("action_8")
        self.menuRe.addAction(self.action_5)
        self.menu_2.addAction(self.action_7)
        self.menu_2.addAction(self.action_8)
        self.menu.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menuRe.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MonitorManagment)
        QtCore.QMetaObject.connectSlotsByName(MonitorManagment)

    def retranslateUi(self, MonitorManagment):
        _translate = QtCore.QCoreApplication.translate
        MonitorManagment.setWindowTitle(_translate("MonitorManagment", "MonitorManagment"))
        self.ProjectorIndicator.setText(_translate("MonitorManagment", "ПРОЕКТОР"))
        self.label_2.setText(_translate("MonitorManagment", "Проектор"))
        self.ScreenIndicator_2.setText(_translate("MonitorManagment", "2 Экран Включить?"))
        self.ScreenIndicator_1.setText(_translate("MonitorManagment", "1 Экран Включить?"))
        self.ScreenIndicator_3.setText(_translate("MonitorManagment", "3 Экран Включить?"))
        self.label.setText(_translate("MonitorManagment", "Главный зал"))
        self.pushButtonOn.setText(_translate("MonitorManagment", "Включить"))
        self.pushButtonOff.setText(_translate("MonitorManagment", "Выключить"))
        self.pushButtonM1Yes.setText(_translate("MonitorManagment", "Да"))
        self.pushButtonM1No.setText(_translate("MonitorManagment", "Нет"))
        self.pushButtonM3Yes.setText(_translate("MonitorManagment", "Да"))
        self.pushButtonM3No.setText(_translate("MonitorManagment", "Нет"))
        self.pushButtonM2Yes.setText(_translate("MonitorManagment", "Да"))
        self.pushButtonM2No.setText(_translate("MonitorManagment", "Нет"))
        self.pushButtonAllMOn.setText(_translate("MonitorManagment", "Включить все мониторы"))
        self.pushButtonAllMOff.setText(_translate("MonitorManagment", "Выключить все мониторы"))
        self.menuRe.setTitle(_translate("MonitorManagment", "Настройки"))
        self.menu.setTitle(_translate("MonitorManagment", "Служба техподдержки"))
        self.menu_2.setTitle(_translate("MonitorManagment", "Отправить Дмитрию сообщение"))
        self.actionClose.setText(_translate("MonitorManagment", "Close"))
        self.actionOpen.setText(_translate("MonitorManagment", "Open"))
        self.action_5.setText(_translate("MonitorManagment", "Тест"))
        self.action_7.setText(_translate("MonitorManagment", "\"Вышла ошибка\""))
        self.action_8.setText(_translate("MonitorManagment", "\"Монитор или проектор не запустился\""))


